In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [5]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values
print(len(X))


400


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
print(le,X)

LabelEncoder() [[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
print(X_train, X_test, y_train, y_test)

[[1 58 144000]
 [0 59 83000]
 [0 24 55000]
 [0 26 35000]
 [0 58 38000]
 [0 42 80000]
 [0 40 75000]
 [1 59 130000]
 [0 46 41000]
 [0 41 60000]
 [1 42 64000]
 [0 37 146000]
 [0 23 48000]
 [1 25 33000]
 [1 24 84000]
 [0 27 96000]
 [1 23 63000]
 [1 48 33000]
 [1 48 90000]
 [1 42 104000]
 [0 44 39000]
 [1 32 120000]
 [0 38 50000]
 [0 32 135000]
 [0 52 21000]
 [0 53 104000]
 [1 39 42000]
 [1 38 61000]
 [0 36 50000]
 [0 36 63000]
 [0 35 25000]
 [1 35 50000]
 [1 42 73000]
 [0 47 49000]
 [0 59 29000]
 [1 49 65000]
 [0 45 131000]
 [0 31 89000]
 [0 46 82000]
 [0 47 51000]
 [1 26 15000]
 [1 60 102000]
 [0 38 112000]
 [1 40 107000]
 [0 42 53000]
 [1 35 59000]
 [1 48 41000]
 [0 48 134000]
 [0 38 113000]
 [1 29 148000]
 [0 26 15000]
 [1 60 42000]
 [1 24 19000]
 [1 42 149000]
 [0 46 96000]
 [1 28 59000]
 [1 39 96000]
 [1 28 89000]
 [1 41 72000]
 [1 45 26000]
 [0 33 69000]
 [0 20 82000]
 [1 31 74000]
 [1 42 80000]
 [0 35 72000]
 [0 33 149000]
 [1 40 71000]
 [0 51 146000]
 [1 46 79000]
 [1 35 75000]
 [1

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train,X_test)

StandardScaler() [[ 1.02532046e+00  1.92295008e+00  2.14601566e+00]
 [-9.75304830e-01  2.02016082e+00  3.78719297e-01]
 [-9.75304830e-01 -1.38221530e+00 -4.32498705e-01]
 [-9.75304830e-01 -1.18779381e+00 -1.01194013e+00]
 [-9.75304830e-01  1.92295008e+00 -9.25023920e-01]
 [-9.75304830e-01  3.67578135e-01  2.91803083e-01]
 [-9.75304830e-01  1.73156642e-01  1.46942725e-01]
 [ 1.02532046e+00  2.02016082e+00  1.74040666e+00]
 [-9.75304830e-01  7.56421121e-01 -8.38107706e-01]
 [-9.75304830e-01  2.70367388e-01 -2.87638347e-01]
 [ 1.02532046e+00  3.67578135e-01 -1.71750061e-01]
 [-9.75304830e-01 -1.18475597e-01  2.20395980e+00]
 [-9.75304830e-01 -1.47942605e+00 -6.35303205e-01]
 [ 1.02532046e+00 -1.28500455e+00 -1.06988428e+00]
 [ 1.02532046e+00 -1.38221530e+00  4.07691369e-01]
 [-9.75304830e-01 -1.09058306e+00  7.55356227e-01]
 [ 1.02532046e+00 -1.47942605e+00 -2.00722133e-01]
 [ 1.02532046e+00  9.50842613e-01 -1.06988428e+00]
 [ 1.02532046e+00  9.50842613e-01  5.81523798e-01]
 [ 1.02532046e

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
y_pred = classifier.predict(X_test)
print(y_pred)


[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)


[[55  3]
 [ 1 21]]


In [ ]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac)

0.95
